version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erd_backend
    environment:
      MONGODB_URI: ${MONGODB_URI}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - '4000:4000'
    command: ['npm', 'start']

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erd_frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000
